version: '3.2'

services:
    api:
#        image: ghcr.io/engineer-man/piston
        build: ./api
        image: piston:dev
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
            - ./api/src:/piston/src
        tmpfs:
            - /tmp:exec
        environment:
            - NODE_ENV=development
